// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmdJY_H7e4bn1ENifrbNej3FuYkHIizZM',
    appId: '1:388940608397:ios:1d5738e8fdbc67baf143c4',
    messagingSenderId: '388940608397',
    projectId: 'spree-26-flutter',
    storageBucket: 'spree-26-flutter.firebasestorage.app',
    androidClientId: '388940608397-9t20frv41kdjsmq335o6j4mp3d40f6c4.apps.googleusercontent.com',
    iosClientId: '388940608397-6ta15ktdjo9pcvlro6ucunh55js1nch6.apps.googleusercontent.com',
    iosBundleId: 'club.devsoc.spree25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd5H0xMC5UnLz-RunyZGHi0Y9sO31DkG4',
    appId: '1:388940608397:android:24c559f1aa5cbdcff143c4',
    messagingSenderId: '388940608397',
    projectId: 'spree-26-flutter',
    storageBucket: 'spree-26-flutter.firebasestorage.app',
  );

}