// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3p0hqgnY-4jOQwNkwFiUwaeC1VPexvgk',
    appId: '1:388940608397:web:d2c41c4c66c90e70f143c4',
    messagingSenderId: '388940608397',
    projectId: 'spree-26-flutter',
    authDomain: 'spree-26-flutter.firebaseapp.com',
    storageBucket: 'spree-26-flutter.firebasestorage.app',
    measurementId: 'G-47LCN1J7YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd5H0xMC5UnLz-RunyZGHi0Y9sO31DkG4',
    appId: '1:388940608397:android:24c559f1aa5cbdcff143c4',
    messagingSenderId: '388940608397',
    projectId: 'spree-26-flutter',
    storageBucket: 'spree-26-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmdJY_H7e4bn1ENifrbNej3FuYkHIizZM',
    appId: '1:388940608397:ios:d4ce9221f0f85aeef143c4',
    messagingSenderId: '388940608397',
    projectId: 'spree-26-flutter',
    storageBucket: 'spree-26-flutter.firebasestorage.app',
    iosClientId: '388940608397-l6umqrm0a62ue15ujtrjb6e9f54ntidf.apps.googleusercontent.com',
    iosBundleId: 'club.devsoc.spree26',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmdJY_H7e4bn1ENifrbNej3FuYkHIizZM',
    appId: '1:388940608397:ios:4ee8362b1989826ff143c4',
    messagingSenderId: '388940608397',
    projectId: 'spree-26-flutter',
    storageBucket: 'spree-26-flutter.firebasestorage.app',
    iosClientId: '388940608397-jm87rq9bslhmn1h9tdabusnt9d6bpmqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.spree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3p0hqgnY-4jOQwNkwFiUwaeC1VPexvgk',
    appId: '1:388940608397:web:39a16de0ed9a4891f143c4',
    messagingSenderId: '388940608397',
    projectId: 'spree-26-flutter',
    authDomain: 'spree-26-flutter.firebaseapp.com',
    storageBucket: 'spree-26-flutter.firebasestorage.app',
    measurementId: 'G-F26GT59Q6S',
  );

}